apiVersion: v2
name: swapica
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: "1.16.0"

dependencies:
  - name: swapica-svc
    version: 0.1.0
    condition: swapica-svc.enabled
  - name: web-client
    version: 0.1.0
    condition: web-client.enabled
  - name: aggregator
    version: 0.1.0
    condition: aggregator.enabled
  - name: landing
    version: 0.1.0
    condition: landing.enabled

