version: '3.3'

services:
  traefik:
    image: traefik:v2.0
    ports:
      - "80:80"
      - "8081:8080"
    volumes:
      - ./configs/traefik.yaml:/traefik.yaml
  cop:
    image: tokend/traefik-cop:1.0.0
    restart: unless-stopped
    depends_on:
      - traefik
    environment:
      - KV_VIPER_FILE=/config.yaml
    volumes:
      - ./configs/cop.yaml:/config.yaml
    entrypoint: sh -c "traefik-cop run"
  upstream:
    image: nginx
    restart: unless-stopped
    depends_on:
      - traefik
    volumes:
      - ./configs/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8000:80"
  swapica:
    image: swapica/swapica:v1.0.0-rc.20
    restart: unless-stopped
    depends_on:
      - cop
    environment:
      - KV_VIPER_FILE=/config.yaml
    volumes:
      - ./configs/swapica.yaml:/config.yaml
    entrypoint: sh -c "swapica-svc run service"
  rpc-proxy:
    image: swapica/rpc-proxy:v1.0.0-rc.0
    restart: unless-stopped
    environment:
      - KV_VIPER_FILE=/config.yaml
    depends_on:
      - cop
    volumes:
      - ./configs/rpc-proxy.yaml:/config.yaml
    entrypoint: sh -c "rpc-proxy-svc run service"
  landing: 
    image: swapica/landing:v1.0.0-rc.11
    restart: unless-stopped
    volumes:
      - ./configs/client.js:/usr/share/nginx/html/env.js
    ports:
      - "8070:80"
  web_client:
    image: swapica/web:v1.0.0-rc.25
    restart: unless-stopped
    volumes:
     - ./configs/client.js:/usr/share/nginx/html/env.js
    ports:
      - "8060:80"

  indexer-goerli:
    image: swapica/indexer:v0.1.0-rc.5
    restart: unless-stopped
    depends_on:
      - order-aggregator
    environment:
      - KV_VIPER_FILE=/config.yaml
    volumes:
      - ./configs/indexer-goerli.yaml:/config.yaml
    entrypoint: sh -c "indexer-svc run service"
  indexer-fuji:
    image: swapica/indexer:v0.1.0-rc.5
    restart: unless-stopped
    depends_on:
      - order-aggregator
    environment:
      - KV_VIPER_FILE=/config.yaml
    volumes:
      - ./configs/indexer-fuji.yaml:/config.yaml
    entrypoint: sh -c "indexer-svc run service"
  indexer-sepolia:
    image: swapica/indexer:v0.1.0-rc.5
    restart: unless-stopped
    depends_on:
      - order-aggregator
    environment:
      - KV_VIPER_FILE=/config.yaml
    volumes:
      - ./configs/indexer-sepolia.yaml:/config.yaml
    entrypoint: sh -c "indexer-svc run service"
  indexer-q-testnet:
    image: swapica/indexer:v0.1.0-rc.5
    restart: unless-stopped
    depends_on:
      - order-aggregator
    environment:
      - KV_VIPER_FILE=/config.yaml
    volumes:
      - ./configs/indexer-q-testnet.yaml:/config.yaml
    entrypoint: sh -c "indexer-svc run service"
  indexer-avalanche:
    image: swapica/indexer:v0.1.0-rc.5
    restart: unless-stopped
    depends_on:
      - order-aggregator
    environment:
      - KV_VIPER_FILE=/config.yaml
    volumes:
      - ./configs/indexer-avalanche.yaml:/config.yaml
    entrypoint: sh -c "indexer-svc run service"

  order-aggregator:
    image: swapica/order-aggregator:v0.1.0-rc.9
    restart: unless-stopped
    depends_on:
      - orders_db
      - cop
    environment:
      - KV_VIPER_FILE=/config.yaml
    volumes:
      - ./configs/order-aggregator.yaml:/config.yaml
    entrypoint: sh -c "order-aggregator-svc migrate up && order-aggregator-svc run service"
  orders_db:
    image: tokend/postgres-ubuntu:9.6
    stop_grace_period: 1s
    restart: unless-stopped
    environment:
      - POSTGRES_USER=orders
      - POSTGRES_PASSWORD=orders
      - POSTGRES_DB=orders
      - PGDATA=/pgdata
    volumes:
      - orders-data:/pgdata
  relayer:
    image: swapica/relayer:v0.1.0-rc.2
    restart: unless-stopped
    depends_on:
      - cop
    environment:
      - KV_VIPER_FILE=/config.yaml
    volumes:
      - ./configs/relayer.yaml:/config.yaml
    entrypoint: sh -c "relayer-svc run service"

volumes:
  orders-data:
