version: '3.3'

services:
  upstream:
    image: nginx
    restart: unless-stopped
    volumes:
      - ./configs/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8000:80"
  swapica:
    image:
    restart: unless-stopped
    environment:
      - KV_VIPER_FILE=/config.yaml
    ports:
      - "8040:80"
    volumes:
      - ./configs/swapica.yaml:/config.yaml
    entrypoint: sh -c "swapica-svc run service"