version: '3.3'

services:
  upstream:
    image: nginx
    restart: unless-stopped
    volumes:
      - ./configs/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8000:80"
  swapica:
    image: swapica/swapica:v1.0.0-rc.0
    restart: unless-stopped
    environment:
      - KV_VIPER_FILE=/config.yaml
    ports:
      - "8040:80"
    volumes:
      - ./configs/swapica.yaml:/config.yaml
    entrypoint: sh -c "swapica-svc run service"
  rpc-proxy:
    image: swapica/rpc-proxy:v0.1.0
    restart: unless-stopped
    environment:
      - KV_VIPER_FILE=/config.yaml
    ports:
      - "8050:80"
    volumes:
      - ./configs/rpc-proxy.yaml:/config.yaml
    entrypoint: sh -c "rpc-proxy-svc run service"
  landing: 
    image: swapica/landing:v1.0.0-rc.3
    restart: unless-stopped
    volumes:
      - ./configs/client.js:/usr/share/nginx/html/env.js
    ports:
      - 8070:80
  web_client:
    image: swapica/web:v1.0.0-rc.3
    restart: unless-stopped
    volumes:
     - ./configs/client.js:/usr/share/nginx/html/env.js
    ports:
      - 8060:80
