# Default values for swapica-svc.
# This is a YAML-formatted file.
# Declare variables to be passed into your swapica-svcs.

replicaCount: 1

image:
  repository: swapica/swapica
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "v1.0.0-rc.0"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

vpa: false

env:
  enable: true
  data:
  - name: KV_VIPER_FILE
    value: /config/config.yaml

arg:
  enable: false

command:
  enable: true
  data:
  - "sh"
  - "-c"
  - "swapica-svc run service"

config:
  create: true
  name: config.yaml
  mountPath: "/config"
  data:
    cop:
      disabled: true
    data:
      chains:
      - chain_params:
          chain_hex_id: "0x5"
          chain_id: 97
          explorer_url: https://explorer.binance.org/smart-testnet
          native_decimals: 18
          native_symbol: BNB
          rpc: https://data-seed-prebsc-1-s1.binance.org:8545
        confirmations: 12
        icon: https://chainlist.org/_next/image?url=https%3A%2F%2Fdefillama.com%2Fchain-icons%2Frsz_ethereum.jpg&w=64&q=75
        id: chapel
        name: BSC Testnet
        rpc_endpoint: https://data-seed-prebsc-1-s1.binance.org:8545
        swap_contract: 0x9cCA217894fb8d87580B3a07F8735f4AA178D456
        type: evm
      - chain_params:
          chain_hex_id: "0x5"
          chain_id: 5
          explorer_url: https://goerli.etherscan.io/
          native_decimals: 18
          native_symbol: ETH
          rpc: https://goerli.infura.io/v3/67e22c92921e42839c983fbdecf33525
        confirmations: 12
        icon: https://chainlist.org/_next/image?url=https%3A%2F%2Fdefillama.com%2Fchain-icons%2Frsz_ethereum.jpg&w=64&q=75
        id: goerli
        name: Ethereum Goerli
        rpc_endpoint: https://goerli.infura.io/v3/d6e902b4a77c4c46b48cfe7dea615a69
        swap_contract: 0x30B5f576Fb0Ab3837fFB8Ec68A6c4cA2b335E8ca
        type: evm
      tokens:
      - chains:
        - chain_id: goerli
          contract_address: 0x5a735AefD4F924884414d24d4F6acA128f85C70b
          token_type: erc20
        - chain_id: chapel
          contract_address: 0x2b52FE12464e1C233628B4A5eb37803485f49A4F
          token_type: erc20
        icon: https://etherscan.io/token/images/tether_32.png
        id: "1"
        name: Tether USDT
        symbol: USDT
        type: fungible
    listener:
      addr: :8000
    log:
      disable_sentry: true
      level: debug
    signer:
      eth_signer: 19cbf23b785cbc5464be38225cc0dc2942e82b89bbeb0323ad16dd6e8ff5e6b2

                

serviceAccount:
  # Specifies whether a service account should be created
  create: false
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname swapica-svc
  name: ""

podAnnotations: {}

podSecurityContext: {}
# fsGroup: 2000

securityContext:
  # capabilities:
  #   drop:
  #   - ALL
  readOnlyRootFilesystem: true
  # runAsNonRoot: true
  runAsUser: 1000
  capabilities:
    drop:
    - ALL

service:
  type: ClusterIP
  port: 8000

ingress:
  enabled: true
  className: ""
  annotations:
    certmanager.k8s.io/cluster-issuer: letsencrypt
    cert-manager.io/cluster-issuer: letsencrypt
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
    nginx.ingress.kubernetes.io/configuration-snippet: |
        # INFO https://github.com/kubernetes/ingress-nginx/issues/2535
        # Somehow these headers got duplicated in requests, so unsetting them here
        more_clear_headers 'Access-Control-Allow-Origin' 'Access-Control-Allow-Credentials';
        if ($request_method = 'OPTIONS') {
            add_header 'Access-Control-Allow-Origin' $http_origin always;
            add_header 'Access-Control-Allow-Credentials' 'true' always;
            add_header 'Access-Control-Allow-Methods' 'GET, POST, PUT, PATCH, OPTIONS, DELETE' always;
            add_header 'Access-Control-Allow-Headers' 'DNT,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range,Signature,Account-Id' always;
            add_header 'Access-Control-Max-Age' 1728000 always;
            add_header 'Content-Type' 'text/plain charset=UTF-8' always;
            add_header 'Content-Length' 0 always;
            return 204;
        }
        if ($request_method ~ '(GET|POST|PUT|PATCH|DELETE)') {
            add_header 'Access-Control-Allow-Origin' $http_origin always;
            add_header 'Access-Control-Allow-Credentials' 'true' always;
            add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS' always;
            add_header 'Access-Control-Allow-Headers' 'DNT,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range,Signature,Account-Id' always;
        }
  hosts:
  - host: api.preprod.swapica.io
    paths:
    - path: /
      pathType: ImplementationSpecific
  tls:
  - secretName: api-tls
    hosts:
    - api.preprod.swapica.io


resources:
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

tests: false

nodeSelector: {}

tolerations: []

affinity: {}
