log:
  level: debug
  disable_sentry: true

collector:
  endpoint: "http://order-aggregator/integrations/order-aggregator"
  request_timeout: 3s

network:
  rpc: "http://rpc-proxy/integrations/rpc-proxy/fuji"
  contract: "0xCb4c864ec5355E6E01dB7118547cD0b355b8A2f4"
  chain_id: 43113
  index_period: 20s # period of contract calls for fetching events, should be > average_block_time
  use_websocket: true
  ws: "wss://api.avax-test.network/ext/bc/C/ws" # required to subscribe to blocks
  # optional fields
  block_range: 2047 # max difference between start and end block for eth_getLogs call, e.g. for Fuji Ankr RPC it's 3000, for Infura see https://docs.infura.io/infura/networks/ethereum/json-rpc-methods/eth_getlogs#limitations
  override_last_block: "21037746" # if set, updates the last block in DB and catches up from it; need to use on sync problems and disable after restoring normal sync
  request_timeout: 7s
