log:
  level: debug
  disable_sentry: true

collector:
  endpoint: "http://order-aggregator/integrations/order-aggregator"
  request_timeout: 3s

network:
  rpc: "http://rpc-proxy/integrations/rpc-proxy/q_testnet"
  contract: "0xB9Fa73D0fF6D98c839e15B0a513be899e9671a92"
  chain_id: 35443
  index_period: 30s
  # on troubles see more fields in indexer-fuji.yaml
  override_last_block: "5787243"
  request_timeout: 7s
