log:
  level: debug
  disable_sentry: true

collector:
  endpoint: "http://order-aggregator/integrations/order-aggregator"
  request_timeout: 3s

network:
  rpc: "http://rpc-proxy/integrations/rpc-proxy/sepolia"
  contract: "0xB2452930B6Cd3da604f0B24639ce5808E8E3dF03"
  chain_id: 11155111
  index_period: 30s
  # on troubles see more fields in indexer-fuji.yaml
  request_timeout: 7s
  override_last_block: "3359098"
