log:
  level: debug
  disable_sentry: true

collector:
  endpoint: "http://order-aggregator/integrations/order-aggregator"
  request_timeout: 3s

network:
  rpc: "http://rpc-proxy/integrations/rpc-proxy/fuji"
  contract: "0xD99105Cc612dbfFb3be1437eCe534A812BfbD35a"
  chain_id: 43113
  index_period: 20s # period of contract calls for fetching events, should be > average_block_time
  use_websocket: true
  ws: "wss://api.avax-test.network/ext/bc/C/ws" # required to subscribe to blocks
  override_last_block: "21233282" # block to begin with
  # optional fields
  # block_range: 3000 # max difference between start and end block for eth_getLogs call, e.g. for Fuji Ankr RPC it's 3000, for Infura see https://docs.infura.io/infura/networks/ethereum/json-rpc-methods/eth_getlogs#limitations
  request_timeout: 7s
