log:
  level: debug
  disable_sentry: true

collector:
  endpoint: "http://order-aggregator/integrations/order-aggregator"
  request_timeout: 3s

network:
  rpc: "http://rpc-proxy/integrations/rpc-proxy/goerli"
  contract: "0x7ee8394FcdB1EB17FEfD3E2A5D97fDB0cBa51a7F"
  chain_id: 5
  index_period: 30s
  # on troubles see more fields in indexer-fuji.yaml
  request_timeout: 7s
