log:
  level: debug
  disable_sentry: true

collector:
  endpoint: "http://order-aggregator/integrations/order-aggregator"
  request_timeout: 3s

network:
  rpc: "http://rpc-proxy/integrations/rpc-proxy/sepolia"
  contract: "0xc453792E6C896f0808BC45E271F811d2010cA62e"
  chain_id: 11155111
  index_period: 30s
  use_websocket: true
  ws: "wss://sepolia.infura.io/ws/v3/YOUR_API_KEY" # required to subscribe to blocks
  # on troubles see more fields in indexer-fuji.yaml
  request_timeout: 7s
  override_last_block: "3313750"
