log:
  level: debug
  disable_sentry: true

collector:
  endpoint: "http://order-aggregator/integrations/order-aggregator"
  request_timeout: 1s

network:
  rpc: "http://rpc-proxy/integrations/rpc-proxy/fuji"
  contract: "0xd345c8E2Cc5AD196936C686223D7915349AaDbAd"
  chain_id: 43113
  index_period: 20s # period of contract calls for fetching events, should be > average_block_time
  # optional fields
  block_range: 3000 # max difference between start and end block on eth_getLogs call, e.g. for Fuji Ankr RPC it's 3000
  override_last_block: "18893540" # if set, updates the last block in DB and catches up from it; need to use on sync problems and disable after restoring normal sync
  request_timeout: 7s
