log:
  level: debug
  disable_sentry: true

db:
  url: "postgres://orders:orders@orders_db/orders?sslmode=disable"

listener:
  addr: :80

chains:
  url: "http://swapica/v1/chains"

notifications:
  push_url: "https://backend.epns.io/apis" # prod; use https://backend-staging.epns.io/apis for staging
  channel_address: ""
  push_comm_address: "0xb3971bcef2d791bc4027bbfedfb47319a4aaaaaa" # Ethereum Mainnet and Goerli
  private_key: ""

cop:
  disabled: false
  endpoint: "http://cop"
  upstream: "http://order-aggregator"
  service_name: order-aggregator
  service_port: 80
