log:
  level: debug
  disable_sentry: true

listener:
  addr: :80

transactor:
  private_key: "transaction sender"

chains:
  list:
    - name: "sepolia"
      contract: "0xFbae44a113A6f07687b180605f425e43066a6179" # relayer contract
      rpc: "http://rpc-proxy/integrations/rpc-proxy/sepolia"
      chain_id: 5
    - name: "fuji"
      contract: "0x514BCFEBe3Dc2C04d14Ae67FEd49481C8d7E090C"
      rpc: "http://rpc-proxy/integrations/rpc-proxy/fuji"
      chain_id: 43113

cop:
  disabled: false
  endpoint: "http://cop"
  upstream: "http://relayer"
  service_name: relayer
  service_port: 80