log:
  level: debug
  disable_sentry: true

listener:
  addr: :80

networks:
  mainnet: "https://mainnet.infura.io/v3/YOUR_API_KEY"
  goerli: "https://goerli.infura.io/v3/YOUR_API_KEY"
  sepolia: "https://sepolia.infura.io/v3/YOUR_API_KEY"

cop:
  disabled: true
