log:
  level: debug
  disable_sentry: true

listener:
  addr: :80

data:
  tokens: # list of supported tokens
    - id: "1"
      name: "Tether USDT"
      symbol: "USDT"
      icon: "https://etherscan.io/token/images/tether_32.png"
      type: fungible
      chains:
        - chain_id: "goerli"
          token_type: erc20
          contract_address: "0x5a735AefD4F924884414d24d4F6acA128f85C70b"
        - chain_id: "chapel"
          token_type: erc20
          contract_address: "0x2b52FE12464e1C233628B4A5eb37803485f49A4F"
  chains:
    - id: "chapel"
      name: "BSC Testnet"
      icon: "https://chainlist.org/_next/image?url=https%3A%2F%2Fdefillama.com%2Fchain-icons%2Frsz_ethereum.jpg&w=64&q=75"
      type: "evm"
      swap_contract: "0x9cCA217894fb8d87580B3a07F8735f4AA178D456" # address of swap contract
      rpc_endpoint: "https://data-seed-prebsc-1-s1.binance.org:8545" # network rpc
      confirmations: 12
      chain_params:
        chain_id: 97
        native_symbol: "BNB"
        native_decimals: 18
        rpc: "https://data-seed-prebsc-1-s1.binance.org:8545"
        explorer_url: "https://explorer.binance.org/smart-testnet"
        chain_hex_id: "0x5"
    - id: "goerli"
      name: "Ethereum Goerli"
      icon: "https://chainlist.org/_next/image?url=https%3A%2F%2Fdefillama.com%2Fchain-icons%2Frsz_ethereum.jpg&w=64&q=75"
      type: "evm"
      swap_contract: "0x30B5f576Fb0Ab3837fFB8Ec68A6c4cA2b335E8ca" # address of swap contract
      rpc_endpoint: "http://rpc-proxy/goerli" # network rpc
      confirmations: 12
      chain_params:
        chain_id: 5
        native_symbol: "ETH"
        native_decimals: 18
        rpc: "http://rpc-proxy/goerli"
        explorer_url: "https://goerli.etherscan.io/"
        chain_hex_id: "0x5"


signer:
  eth_signer: ""

cop:
  disabled: true
