log:
  level: debug
  disable_sentry: true

listener:
  addr: :80

data:
  tokens: # list of supported tokens
    - id: "1"
      name: "Native currency"
      symbol: "ETH"
      icon: "https://raw.githubusercontent.com/Swapica/assets/master/tokens/eth/ETH.png"
      type: fungible
      chains:
        - chain_id: "goerli"
          token_type: native
          contract_address: "0xEeeeeEeeeEeEeeEeEeEeeEEEeeeeEeeeeeeeEEeE"
        - chain_id: "sepolia"
          token_type: native
          contract_address: "0xEeeeeEeeeEeEeeEeEeEeeEEEeeeeEeeeeeeeEEeE"
          max_amount: 100000000000000000
    - id: "2"
      name: "Native currency"
      symbol: "AVAX"
      icon: "https://raw.githubusercontent.com/Swapica/assets/master/tokens/avax/AVAX.png"
      type: fungible
      chains:
        - chain_id: "fuji"
          token_type: native
          contract_address: "0xEeeeeEeeeEeEeeEeEeEeeEEEeeeeEeeeeeeeEEeE"
    - id: "3"
      name: "Native currency"
      symbol: "Q"
      icon: "https://raw.githubusercontent.com/Swapica/assets/master/tokens/q/Q.png"
      type: fungible
      chains:
        - chain_id: "q-testnet"
          token_type: native
          contract_address: "0xEeeeeEeeeEeEeeEeEeEeeEEEeeeeEeeeeeeeEEeE"
    - id: "4"
      name: "Mock1"
      symbol: "Mock1"
      icon: "https://raw.githubusercontent.com/Swapica/assets/master/tokens/eth/ETH.png"
      type: fungible
      chains:
        - chain_id: "goerli"
          token_type: erc20
          contract_address: "0x9109c4b08eE452D6145D9496F9542A13f48701E4"
          max_amount: 100000000000000000
    - id: "5"
      name: "Mock2"
      symbol: "Mock2"
      icon: "https://raw.githubusercontent.com/Swapica/assets/master/tokens/eth/ETH.png"
      type: fungible
      chains:
        - chain_id: "goerli"
          token_type: erc20
          contract_address: "0xd0485747e4e1ef7109041ee9108f27474955f570"
          max_amount: 1000000
  chains:
    - id: "fuji"
      name: "Avalanche Testnet"
      icon: "https://raw.githubusercontent.com/Swapica/assets/master/chains/avalanche/avalanche.png"
      type: "evm"
      swap_contract: "0x9493e2970931D9a182AB99290B3F43347F1b8b9a"
      rpc_endpoint: "http://rpc-proxy/integrations/rpc-proxy/fuji" # internal: for RPC calls
      confirmations: 12
      chain_params:
        chain_id: 43113
        native_symbol: "AVAX"
        native_decimals: 18
        rpc: "http://rpc-proxy/integrations/rpc-proxy/fuji" # external: appears on the client side
        explorer_url: "https://cchain.explorer.avax-test.network"
        chain_hex_id: "0xa869"
        chain_type: "testnet"
        public_rpc: "https://api.avax-test.network/ext/bc/C/rpc"
    - id: "goerli"
      name: "Ethereum Goerli"
      icon: "https://raw.githubusercontent.com/Swapica/assets/master/chains/ethereum/ethereum.png"
      type: "evm"
      swap_contract: "0xb3Ed05F9289F3aCcB61Fc418166b58171D8E0f06"
      rpc_endpoint: "http://rpc-proxy/integrations/rpc-proxy/goerli"
      confirmations: 12
      chain_params:
        chain_id: 5
        native_symbol: "ETH"
        native_decimals: 18
        rpc: "http://rpc-proxy/integrations/rpc-proxy/goerli"
        explorer_url: "https://goerli.etherscan.io/"
        chain_hex_id: "0x5"
        chain_type: "testnet"
        public_rpc: "https://eth-goerli.public.blastapi.io"
    - id: "sepolia"
      name: "Ethereum Sepolia"
      icon: "https://raw.githubusercontent.com/Swapica/assets/master/chains/ethereum/ethereum.png"
      type: "evm"
      swap_contract: "0xFEb582Bc9a161380769aFaA56d84f8cf89783c8a"
      rpc_endpoint: "http://rpc-proxy/integrations/rpc-proxy/sepolia"
      confirmations: 12
      chain_params:
        chain_id: 11155111
        native_symbol: "ETH"
        native_decimals: 18
        rpc: "http://rpc-proxy/integrations/rpc-proxy/sepolia"
        explorer_url: "https://sepolia.etherscan.io/"
        chain_hex_id: "0xaa36a7"
        chain_type: "mainnet"
        public_rpc: "https://eth-sepolia.public.blastapi.io"
    - id: "q-testnet"
      name: "Q Testnet"
      icon: "https://raw.githubusercontent.com/Swapica/assets/master/chains/q/q.png"
      swap_contract: "0xB9Fa73D0fF6D98c839e15B0a513be899e9671a92"
      rpc_endpoint: "http://rpc-proxy/integrations/rpc-proxy/q_testnet"
      type: "evm"
      confirmations: 12
      chain_params:
        chain_id: 35443
        native_symbol: "Q "
        native_decimals: 18
        rpc: "http://rpc-proxy/integrations/rpc-proxy/q_testnet"
        explorer_url: "https://explorer.qtestnet.org/"
        chain_hex_id: "0x8a73"
        chain_type: "mainnet"
        public_rpc: "https://rpc.qtestnet.org"


signer:
  eth_signer: "private key of address from getSigners contract method"

cop:
  disabled: false
  endpoint: "http://cop"
  upstream: "http://swapica"
  service_name: swapica
  service_port: 80
