log:
  level: debug
  disable_sentry: true

listener:
  addr: :80

data:
  tokens: # list of supported tokens
    - id: "1"
      name: "Tether USDT"
      symbol: "USDT"
      icon: "https://raw.githubusercontent.com/Swapica/assets/master/tokens/usdt/USDT.png"
      type: fungible
      chains:
        - chain_id: "goerli"
          token_type: erc20
          contract_address: "0xcf6b39a6F390132CE852472B6BaA213F6aE2F416"
        - chain_id: "fuji"
          token_type: erc20
          contract_address: "0xd7F28eC57bEaADd392E112c5735C5992303C0dF9"
    - id: "2"
      name: "Native currency"
      symbol: "ETH"
      icon: "https://raw.githubusercontent.com/Swapica/assets/master/tokens/eth/ETH.png"
      type: fungible
      chains:
        - chain_id: "goerli"
          token_type: native
          contract_address: "0xEeeeeEeeeEeEeeEeEeEeeEEEeeeeEeeeeeeeEEeE"
        - chain_id: "fuji"
          token_type: native
          contract_address: "0xEeeeeEeeeEeEeeEeEeEeeEEEeeeeEeeeeeeeEEeE"
  chains:
    - id: "fuji"
      name: "Avalanche Testnet"
      icon: "https://raw.githubusercontent.com/Swapica/assets/master/chains/ethereum/ethereum.png"
      type: "evm"
      swap_contract: "0x29dA1560DD6AbAaa522Edb39E84F99191819f8C4" # address of swap contract
      rpc_endpoint: "https://rpc.ankr.com/avalanche_fuji" # network rpc
      confirmations: 12
      chain_params:
        chain_id: 43113
        native_symbol: "AVAX"
        native_decimals: 18
        rpc: "https://rpc.ankr.com/avalanche_fuji"
        explorer_url: "https://cchain.explorer.avax-test.network"
        chain_hex_id: "0xa869"
    - id: "goerli"
      name: "Ethereum Goerli"
      icon: "https://raw.githubusercontent.com/Swapica/assets/master/chains/ethereum/ethereum.png"
      type: "evm"
      swap_contract: "0xC403A5600F396AF9b5135E2Ab65446288169108A" # address of swap contract
      rpc_endpoint: "http://rpc-proxy/integrations/rpc-proxy/goerli" # network rpc
      confirmations: 12
      chain_params:
        chain_id: 5
        native_symbol: "ETH"
        native_decimals: 18
        rpc: "http://rpc-proxy/integrations/rpc-proxy/goerli"
        explorer_url: "https://goerli.etherscan.io/"
        chain_hex_id: "0x5"


signer:
  eth_signer: ""

cop:
  disabled: true
